<!--
onconnect = function (e) {
  y(); // will "report the error"
  // onerror is null so it'll be "not handled", and the error should be
  // reported to the user, although we don't test that here
  // make sure we don't fire an error event on the message port or the
  // SharedWorker object
}


/*
-->
<!doctype html>
<title>shared worker, no error event on worker or port</title>
<script src="/resources/testharness.js"></script>
<script src="/resources/testharnessreport.js"></script>
<div id=log></div>
<script>
async_test(function() {
  var worker = new SharedWorker('#', '');
  worker.addEventListener('error', this.step_func(function(e) {
    assert_unreached('error on worker');
  }), false);
  worker.port.addEventListener('error', this.step_func(function(e) {
    assert_unreached('error on port');
  }), false);
  setTimeout(this.step_func(function() {
    this.done();
  }), 500);
});
</script>
<!--
*/
//-->